### ISSUE TITLE
"14-Day Trial of BackupforWP" Promo Notification Reappears on Every Plugin Settings Page After Dismissal.

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/wp-database-backup#103]
This issue occurs after the latest update version 7.2, 14-Day Trial of BackupforWP" Promo Notification Reappears on Every Plugin Settings Page After Dismissal.

Reference ticket: https://wordpress.org/support/topic/free-trial-notice-does-not-dismiss/

Reference SS: https://paste.pics/S0Q2C

**Comment by MohammedAkramU7** [comment]
Another user https://magazine3.in/conversation/313270?folder_id=21

**Comment by akshaywali** [comment]
pushed in version 7.3
