### ISSUE TITLE
Need to modify the UI of the "Access your Data" button under the Cloud Backup section

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/wp-database-backup#105]
Need to modify the UI of the "Access your Data" button under the Cloud Backup section

Ref screenshot: https://monosnap.com/direct/eTzYI9CtEoFIax6eAlcSApjOW8wkjj

Ref ticket: https://magazine3.in/conversation/313570?folder_id=27

**Comment by akshaywali** [comment]
pushed in 7.4
