### ISSUE TITLE
UI/UX issues

### ISSUE THREAD

**Issue by WasimM3** [ahmedkaludi/wp-database-backup#11]
- [ ] Some gab should be there
![gap-needed](https://user-images.githubusercontent.com/53761154/207874640-9892a64d-be3c-489f-866b-881023884471.png)

- [ ] Is Author info required?
![author-name](https://user-images.githubusercontent.com/53761154/207874778-fa0e5dda-9470-4740-968c-e4ef7e3f324e.png)

**Comment by Sanjeevsetu** [comment]
its done
