### ISSUE TITLE
changes

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/wp-database-backup#16]
- [x] whats the use of alert: https://take.ms/S8SAB - remove rest of them 

- [x] Help Tab with proper support form
- [x] support sticky icon: see red bubble icon on https://ampforwp.com/
- [x] remove from the tools to main menu as "Backups"
- [x] removal of Pro messages
- [x] remove https://take.ms/vuvAM
- [x] deactivation feedback form 
- [x] newsletter on activation
- [x] https://take.ms/yuDOU
- [x] https://take.ms/W7kfl
- [x] https://take.ms/p5mKh
- [x] https://take.ms/pqhZu

**Comment by akshaywali** [comment]
![StatusIndicator+2022-12-17+15-55-41](https://user-images.githubusercontent.com/36995680/208357122-220e85c5-8178-47bd-aefb-5a30f481361f.png)


Messages and Alerts are getting fetched from http://wpseeds.com/notifier/wp-database-backup.xml

**Comment by akshaywali** [comment]
update pushed in version 6.0
