### ISSUE TITLE
Sort by dates option showing listing backup files alphabetically case sensitive

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/wp-database-backup#27]
When the user downloads the backup and sorts them by dates then it is listing months alphabetically wise, hence it is working as alphabetic case sensitive like the first will be April as it started from "A" irrespective of whether anyone has a backup in January.

Reference ticket -: https://magazine3.in/conversation/91328?folder_id=4

**Comment by akshaywali** [comment]
![image](https://github.com/ahmedkaludi/wp-database-backup/assets/36995680/9e1f561d-825c-4a9a-8438-5f123c2ad375)

We have updated the date format as time ago format and it is working fine .
