### ISSUE TITLE
Need to add a option for scheduling the Complete Backup.

### ISSUE THREAD

**Issue by ankit644** [ahmedkaludi/wp-database-backup#29]
Ref ticket: https://magazine3.in/conversation/99069?folder_id=11

**Comment by akshaywali** [comment]
Added option in Commit  https://github.com/ahmedkaludi/wp-database-backup/commit/9253222cd6260191f0072faa2221e9d4d6d39e15

**Comment by akshaywali** [comment]
Pushed in update 6.3
