### ISSUE TITLE
Google Drive backup is not being configured, and there are also multiple issues.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/wp-database-backup#44]
1. When we are trying to configure the Google Drive back but it's not being configured
Ref video: https://monosnap.com/direct/dVndUMsMudi7xEPgUi4mBiIWDNoCXo

2. The issue with taking backup to local backup and email
3. Full backups are not saved to the local location in "Save Backups to."
4. Icons for the locations of saved backups are displayed incorrectly
5. The number of saves to be retained is not respected.
6. A huge amount (~15GBs) of data is saved to /wp-content/uploads/db-backup

Ref ticket: https://magazine3.in/conversation/123549?folder_id=29

**Comment by akshaywali** [comment]
Pushed in update 6.3
