### ISSUE TITLE
The backup progress bar gets stuck while creating the backup

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/wp-database-backup#53]
The backup progress bar gets stuck while creating the backup.

Ref screenshot: https://monosnap.com/direct/k2SDXk5AFrueGUbU0Xmk0IppF87fpP

Ref ticket: https://magazine3.in/conversation/152934?folder_id=27

**Comment by Sdaud1950** [comment]
Same issue with this user:

https://magazine3.in/conversation/131160?folder_id=29

Ref screenshoot: https://prnt.sc/pLIYbXCnctBh

**Comment by akshaywali** [comment]
pushed in 6.4
