### ISSUE TITLE
The option Auto Backup is not working for DropBox

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/wp-database-backup#58]
The option Auto Backup is not working for DropBox and the data has not been stored

Ref ticket: https://magazine3.in/conversation/145624?folder_id=27

**Comment by askcode21** [comment]
another user reported this issue, even after configuration correctly and authentication, it shows not-configured.

Reference ticket: https://wordpress.org/support/topic/dropbox-showing-authenticated-but-not-configured/
