### ISSUE TITLE
Warnings  is showing on wp database-backup.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/wp-database-backup#59]
Parse error: syntax error, unexpected ')' in /home/89/94/2019489/rustsol/web/wp-content/plugins/wp-database-backup/includes/admin/class-wpdb-admin.php on line 349 

Ref ticket: https://magazine3.in/conversation/167541?folder_id=29

**Comment by Sdaud1950** [comment]
Same issue:

https://magazine3.in/conversation/167978?folder_id=29

**Comment by akshaywali** [comment]
fixed in update 6.5.1
