### ISSUE TITLE
Need to add the button to stop the backups.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/wp-database-backup#62]
Ref ticket:-https://magazine3.in/conversation/167361?folder_id=21

Description:-
When the user starts the backup, for some reason it's stuck in between. We need a button feature that will stop the backup and allow the user to start a new backup.

Issue screenshot
https://prnt.sc/vYtDu-W-h1D8

**Comment by akshaywali** [comment]
pushed in update 6.6
