### ISSUE TITLE
Clean List Backup

### ISSUE THREAD

**Issue by new4uweb** [ahmedkaludi/wp-database-backup#71]
Hi guys,

the plugin generated a list of more than 6000 backup records and I can only remove them one by one, how do I remove them all at once?

**Comment by Sanjeevsetu** [comment]
Hi @new4uweb 

Thanks for reaching to us. We currently do not have that option. You have to delete them manually but We are going to add an option for. here is the ticket ref : https://github.com/ahmedkaludi/wp-database-backup/issues/70
