### ISSUE TITLE
Setting in the email notification is not being saved.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/wp-database-backup#78]
The settings in the email notification are not being saved, and the backup file is not being attached to the email.

Ref video : https://monosnap.com/direct/4XlhTTHixiZ07IrOdTCyHnGL1PEZQb 
Ref ticket :https://magazine3.in/conversation/228987?folder_id=29

**Comment by askcode21** [comment]
same concern : https://wordpress.org/support/topic/email-notification-204/

**Comment by Sdaud1950** [comment]
same issue with this user : https://magazine3.in/conversation/243084?folder_id=29

**Comment by akshaywali** [comment]
pushed in version 6.8
