### ISSUE TITLE
wrong polish encoding

### ISSUE THREAD

**Issue by joksik** [ahmedkaludi/wp-database-backup#83]
Hello i start to use this plugin for backups.
My site in "WordPress/Settings/General/Stite Title" have Polish sign like "ó" or "ś".
i notice that when backup is finish (local backup or remote backup for example ftp) it does not display Polish characters but "_".
I attach a printscreen:

![name of site](https://github.com/ahmedkaludi/wp-database-backup/assets/11992667/37f1a3e7-7c48-4b43-8ab6-5ac9cc367381)
![nazwa](https://github.com/ahmedkaludi/wp-database-backup/assets/11992667/c4773fbe-c482-4d65-9220-00b59c97e400)

I use also other plugins that send me some times files but they don’t have this problem and display or save file with correct name encoding

**Comment by akshaywali** [comment]
@joksik  polish encoding issue in the update 6.9 , please  update  and confirm the fix
