### ISSUE TITLE
Plugin error after update to 6.12

### ISSUE THREAD

**Issue by tymik** [ahmedkaludi/wp-database-backup#95]
Hi, my customer updated this plugin yesterday and the site died.

I checked the logs and there's the following error message:

```
PHP Parse error:  syntax error, unexpected ')' in #REDACTED#/wp-content/plugins/wp-database-backup/includes/admin/class-wpdb-admin.php on line 1872,
```

The plugin is in version 6.12
WP version: 6.5.5

**Comment by Sanjeevsetu** [comment]
Hi @tymik 

We have fixed this issue and have released a new version 6.12.1. Please update to that and let us know.

**Comment by tymik** [comment]
Yup, that works, thanks!

Btw. do you have any preventive measures for such cases?
e.g. linting in the pipeline before the version is released?

**Comment by Sanjeevsetu** [comment]
Hi @tymik 

Thanks for the confirmation.

Yes we do proper testing manually or using tools but some time still it happens. We will try our best so that it won't happen again in near future.
